workflows:
  ios-workflow:
    name: iOS Build & TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        XCODE_SCHEME: "LiDARScanner"
        BUNDLE_ID: "com.lidarscanner.LiDarScanner"
        TEAM_ID: "J4FK2D7585"
      groups:
        - App_Store
      xcode: latest

    # triggering disabled - manual builds only
    # triggering:
    #   events:
    #     - push
    #   branch_patterns:
    #     - pattern: master
    #       include: true

    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen

      - name: Generate Xcode project
        script: |
          xcodegen generate

      - name: Fetch signing files
        script: |
          keychain initialize

          # Generate a new RSA key for certificate creation
          openssl genrsa -out "$HOME/cert_key.pem" 2048

          # Debug: show what we have
          echo "Key ID: $APP_STORE_CONNECT_KEY_IDENTIFIER"
          echo "Issuer ID: $APP_STORE_CONNECT_ISSUER_ID"
          echo "Private key length: ${#APP_STORE_CONNECT_PRIVATE_KEY} chars"

          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "@env:APP_STORE_CONNECT_PRIVATE_KEY" \
            --certificate-key "@file:$HOME/cert_key.pem" \
            --create
          keychain add-certificates

      - name: Set up provisioning profile
        script: |
          xcode-project use-profiles

      - name: Increment build number
        script: |
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "@file:$HOME/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_KEY_IDENTIFIER.p8" \
            2>/dev/null || echo "0")
          NEW_BUILD=$((LATEST_BUILD + 1))
          echo "Setting build number to $NEW_BUILD"
          agvtool new-version -all $NEW_BUILD || true

      - name: Build archive
        script: |
          xcodebuild archive \
            -project "LiDARScanner.xcodeproj" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/LiDARScanner.xcarchive \
            -destination "generic/platform=iOS" \
            | xcpretty

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/LiDARScanner.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist ~/export_options.plist \
            | xcpretty

    artifacts:
      - build/ipa/*.ipa
      - build/LiDARScanner.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
      email:
        recipients:
          - mberoz61@gmail.com
        notify:
          success: true
          failure: true
