workflows:
  ios-workflow:
    name: iOS Build & TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        XCODE_SCHEME: "LiDARScanner"
        BUNDLE_ID: "com.lidarscanner.LiDarScanner"
        CERTIFICATE_PASSWORD: "codemagic123"
        TEAM_ID: "J4FK2D7585"
      groups:
        - App_Store
      xcode: latest

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true

    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen

      - name: Generate Xcode project
        script: |
          xcodegen generate

      - name: Set up keychain and certificate
        script: |
          # Create keychain
          keychain initialize

          # Decode and import certificate
          echo $CM_CERTIFICATE | base64 --decode > /tmp/distribution.p12
          keychain add-certificates --certificate /tmp/distribution.p12 --certificate-password "$CERTIFICATE_PASSWORD"

          # Decode and install provisioning profile
          echo $CM_PROVISIONING_PROFILE | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

      - name: Get provisioning profile UUID
        script: |
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c "Print UUID" /dev/stdin <<< $(/usr/bin/security cms -D -i ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision))
          echo "Profile UUID: $PROFILE_UUID"
          echo "PROVISIONING_PROFILE_UUID=$PROFILE_UUID" >> $CM_ENV

      - name: Increment build number
        script: |
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" || echo "0")
          NEW_BUILD=$((LATEST_BUILD + 1))
          echo "Setting build number to $NEW_BUILD"
          cd $CM_BUILD_DIR
          agvtool new-version -all $NEW_BUILD

      - name: Build iOS app
        script: |
          xcodebuild -project "LiDARScanner.xcodeproj" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/LiDARScanner.xcarchive \
            -destination "generic/platform=iOS" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            PROVISIONING_PROFILE="$PROVISIONING_PROFILE_UUID" \
            clean archive

      - name: Export IPA
        script: |
          cat > exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>uploadSymbols</key>
              <true/>
              <key>provisioningProfiles</key>
              <dict>
                  <key>$BUNDLE_ID</key>
                  <string>LiDARScanner AppStore</string>
              </dict>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath build/LiDARScanner.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist exportOptions.plist

    artifacts:
      - build/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - build/LiDARScanner.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
      email:
        recipients:
          - mberoz61@gmail.com
        notify:
          success: true
          failure: true
