workflows:
  ios-workflow:
    name: iOS Build & TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.lidarscanner.LiDarScanner
      vars:
        XCODE_SCHEME: "LiDARScanner"
        BUNDLE_ID: "com.lidarscanner.LiDarScanner"
        TEAM_ID: "J4FK2D7585"
      groups:
        - App_Store
      xcode: latest

    # triggering disabled - manual builds only
    # triggering:
    #   events:
    #     - push
    #   branch_patterns:
    #     - pattern: master
    #       include: true

    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen

      - name: Generate Xcode project
        script: |
          xcodegen generate

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Increment build number
        script: |
          BUILD_NUMBER=$(($(date +%s)/60))
          echo "Setting build number to $BUILD_NUMBER"
          agvtool new-version -all $BUILD_NUMBER || true

      - name: Build archive
        script: |
          xcodebuild archive \
            -project "LiDARScanner.xcodeproj" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/LiDARScanner.xcarchive \
            -destination "generic/platform=iOS" \
            | xcpretty

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/LiDARScanner.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist ~/export_options.plist \
            | xcpretty

    artifacts:
      - build/ipa/*.ipa
      - build/LiDARScanner.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
      email:
        recipients:
          - mberoz61@gmail.com
        notify:
          success: true
          failure: true
