workflows:
  ios-workflow:
    name: iOS Build & TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        XCODE_SCHEME: "LiDARScanner"
        BUNDLE_ID: "com.lidarscanner.LiDarScanner"
        CERTIFICATE_PASSWORD: "codemagic123"
      groups:
        - App_Store
      xcode: latest

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true

    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen

      - name: Generate Xcode project
        script: |
          xcodegen generate

      - name: Set up keychain and certificate
        script: |
          # Create keychain
          keychain initialize

          # Decode and import certificate
          echo $CM_CERTIFICATE | base64 --decode > /tmp/distribution.p12
          keychain add-certificates --certificate /tmp/distribution.p12 --certificate-password "$CERTIFICATE_PASSWORD"

          # Decode and install provisioning profile
          echo $CM_PROVISIONING_PROFILE | base64 --decode > /tmp/profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp /tmp/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Set up code signing settings
        script: |
          xcode-project use-profiles --project "LiDARScanner.xcodeproj"

      - name: Increment build number
        script: |
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" || echo "0")
          NEW_BUILD=$((LATEST_BUILD + 1))
          echo "Setting build number to $NEW_BUILD"
          agvtool new-version -all $NEW_BUILD

      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --project "LiDARScanner.xcodeproj" \
            --scheme "$XCODE_SCHEME" \
            --config "Release"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
      email:
        recipients:
          - mberoz61@gmail.com
        notify:
          success: true
          failure: true
