workflows:
  ios-workflow:
    name: iOS Build & TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        XCODE_SCHEME: "LiDARScanner"
        BUNDLE_ID: "com.lidarscanner.LiDarScanner"
        CERTIFICATE_PASSWORD: "codemagic123"
        TEAM_ID: "J4FK2D7585"
      groups:
        - App_Store
      xcode: latest

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true

    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen

      - name: Generate Xcode project
        script: |
          xcodegen generate

      - name: Set up keychain and certificate
        script: |
          keychain initialize

          echo $CM_CERTIFICATE | base64 --decode > /tmp/distribution.p12
          keychain add-certificates --certificate /tmp/distribution.p12 --certificate-password "$CERTIFICATE_PASSWORD"

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          PROFILE_PATH=~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision
          echo $CM_PROVISIONING_PROFILE | base64 --decode > "$PROFILE_PATH"

          # Extract UUID
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c "Print UUID" /dev/stdin <<< $(/usr/bin/security cms -D -i "$PROFILE_PATH"))
          echo "PROVISIONING_PROFILE_UUID=$PROFILE_UUID" >> $CM_ENV
          echo "Using profile UUID: $PROFILE_UUID"

      - name: Increment build number
        script: |
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" 2>/dev/null || echo "0")
          NEW_BUILD=$((LATEST_BUILD + 1))
          echo "Setting build number to $NEW_BUILD"
          agvtool new-version -all $NEW_BUILD || true

      - name: Build archive
        script: |
          xcodebuild archive \
            -project "LiDARScanner.xcodeproj" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/LiDARScanner.xcarchive \
            -destination "generic/platform=iOS" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            CODE_SIGN_STYLE="Manual" \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE="$PROVISIONING_PROFILE_UUID" | xcpretty

      - name: Export IPA
        script: |
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>com.lidarscanner.LiDarScanner</key>
                  <string>$PROVISIONING_PROFILE_UUID</string>
              </dict>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath build/LiDARScanner.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist exportOptions.plist | xcpretty

    artifacts:
      - build/ipa/*.ipa
      - build/LiDARScanner.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
      email:
        recipients:
          - mberoz61@gmail.com
        notify:
          success: true
          failure: true
