name: LiDARScanner
options:
  bundleIdPrefix: com.lidarscanner
  deploymentTarget:
    iOS: "16.0"

settings:
  base:
    DEVELOPMENT_TEAM: J4FK2D7585
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: "Apple Distribution"

targets:
  LiDARScanner:
    type: application
    platform: iOS
    sources:
      - path: LiDARScanner
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lidarscanner.LiDarScanner
        INFOPLIST_FILE: LiDARScanner/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "1.0"
    info:
      path: LiDARScanner/Info.plist
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        UILaunchScreen: {}
        NSCameraUsageDescription: "This app uses the camera and LiDAR sensor to scan objects."
    entitlements:
      path: LiDARScanner/LiDARScanner.entitlements
      properties: {}
