name: LiDARScanner
options:
  bundleIdPrefix: com.mberoz420
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"

settings:
  base:
    DEVELOPMENT_TEAM: ${XCODE_DEVELOPMENT_TEAM}
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: "iPhone Distribution"

targets:
  LiDARScanner:
    type: application
    platform: iOS
    sources:
      - path: LiDARScanner
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mberoz420.LiDARScanner
        INFOPLIST_FILE: LiDARScanner/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        PROVISIONING_PROFILE_SPECIFIER: ${PROVISIONING_PROFILE_SPECIFIER}
    info:
      path: LiDARScanner/Info.plist
      properties:
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        NSCameraUsageDescription: "This app uses the camera and LiDAR sensor to scan objects."
    entitlements:
      path: LiDARScanner/LiDARScanner.entitlements
      properties: {}
